language: objective-c
osx_image: xcode8.1
script:
    - xcodebuild -project Movies.xcodeproj -scheme Movies -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.1' build test
